name: Run Fast Scan
description: Automates fastscan on source code in github repo every time a commit is done on main

branding:
  icon: check
  color: '#00ff00'
  label: 0.0.1

  

on:
  push:
    branches:
      - main

jobs:
  run-fastscan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull docker image
        run: docker pull castimaging/fast-scan-java-cli
        
      - name: Run Fast Scan
        run: |
         cd ${{ github.workspace }}
          git_folder=$(basename "$(git rev-parse --show-toplevel)") 
          # The git folder name is mapped to the project name
          docker run -v $(pwd):/fastScan/sourceCode castimaging/fast-scan-java-cli /fastScan/sourceCode -n $git_folder
          



